// Every visual decision in the app resolves to one of these tokens.
// Components never hardcode a color/radius/font - they read var(--token),
// and ThemeProvider writes the active theme's values onto :root.
//
// The house style is flat + outlined: solid fills, a single ink color doing
// borders and text, and a hard offset shadow (no blur, no glow). Ink is never
// black - it is a deep tint of the theme's own hue, which is what keeps the
// outlines reading as sticker art rather than as chrome.
//
// `paper`, `paper-2` and `paper-3` are the three stops of the desk gradient
// the grid sits on. `tone-a` through `tone-e` are the pastel titlebars nested
// panes cycle through, so no two stacked windows wear the same colour.
//
// Adding a theme = adding an entry here. Nothing else needs to change.

const DISPLAY = "'Fredoka', ui-rounded, 'Segoe UI', system-ui, sans-serif"
const BODY = "'Nunito', ui-sans-serif, system-ui, -apple-system, sans-serif"
// A real bitmap face. Window titles, chips and small caps are where the
// references carry their whole personality, and a smooth mono cannot fake it.
const LABEL = "'Silkscreen', ui-monospace, 'SF Mono', Menlo, monospace"

// Chart series. Validated with the dataviz palette checker in both light and
// dark modes: lightness band, chroma floor, CVD separation (protan dE 8.8),
// normal-vision separation (dE 20.4) and contrast vs surface all pass. The
// app's pastel tokens fail as a categorical pair - too light, too close - so
// charts get their own deeper pair rather than reusing accent and tier hues.
const SERIES = {
  'series-1': '#c85f7c',
  'series-2': '#4a7fb5',
}

const SHARED = {
  ...SERIES,
  // Fatter ink, rounder corners and a longer shadow throw: the sticker look
  // lives in the outline weight more than in the hue.
  'border-w': '2.5px',
  'shadow-off': '4px',
  'radius-lg': '22px',
  'radius-md': '14px',
  'radius-sm': '9px',
  'font-display': DISPLAY,
  'font-body': BODY,
  'font-label': LABEL,
  'display-weight': '600',
  'display-tracking': '-0.01em',
}

export const THEMES = [
  {
    id: 'sticker',
    name: 'Sticker Club',
    blurb: 'Mint desk, bubblegum ink.',
    scheme: 'light',
    swatch: ['#fdf3f5', '#bdeccd', '#fbc0d6'],
    tokens: {
      ...SHARED,
      paper: '#fdf3f5',
      'paper-2': '#eafaf0',
      'paper-3': '#fdf6dd',
      'paper-grid': 'rgba(214, 120, 145, 0.13)',
      surface: '#fffdfd',
      'surface-2': '#fdeef2',
      bar: '#bdeccd',
      'bar-2': '#fbc0d6',
      ink: '#8e4260',
      'ink-2': '#a9607c',
      'ink-3': '#c08398',
      line: '#f6d9e2',
      accent: '#f9b8cd',
      'accent-2': '#f6a0bd',
      'accent-ink': '#6d3049',
      danger: '#d1466b',
      'tone-a': '#bdeccd',
      'tone-b': '#fbc0d6',
      'tone-c': '#bcd8f7',
      'tone-d': '#fdeaa8',
      'tone-e': '#d9c9f5',
      'tone-ink': '#6d3049',
      'tier-low': '#bdeccd',
      'tier-medium': '#bcd8f7',
      'tier-high': '#fdeaa8',
      'art-s': '60%',
      'art-l': '88%',
      'art-ink': '#8e4260',
      'shadow-color': '#d98aa8',
      'badge-ink': '#6d3049',
    },
  },
  {
    id: 'notepad',
    name: 'Milk & Lilac',
    blurb: 'Cream page, lilac chrome.',
    scheme: 'light',
    swatch: ['#f3f0fb', '#e3d4f9', '#fdf0c2'],
    tokens: {
      ...SHARED,
      paper: '#f3f0fb',
      'paper-2': '#fdf9e9',
      'paper-3': '#eaf2fd',
      'paper-grid': 'rgba(126, 110, 178, 0.14)',
      surface: '#fffdf4',
      'surface-2': '#f0ebfb',
      bar: '#e3d4f9',
      'bar-2': '#fdf0c2',
      ink: '#6b5aa6',
      'ink-2': '#8072b8',
      'ink-3': '#9a8fc7',
      line: '#ded6f4',
      accent: '#c9b8f0',
      'accent-2': '#b6a1ea',
      'accent-ink': '#3f3370',
      danger: '#c25d84',
      'tone-a': '#cfe6fb',
      'tone-b': '#e3d4f9',
      'tone-c': '#fdf0c2',
      'tone-d': '#f9cfe0',
      'tone-e': '#cdeede',
      'tone-ink': '#4a3d80',
      'tier-low': '#cdeede',
      'tier-medium': '#cfe6fb',
      'tier-high': '#fdf0c2',
      'art-s': '55%',
      'art-l': '88%',
      'art-ink': '#6b5aa6',
      'shadow-color': '#b9a9e6',
      'badge-ink': '#3f3370',
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    blurb: 'Graph paper, periwinkle tape.',
    scheme: 'light',
    swatch: ['#e9f1fd', '#bfe3f7', '#d3d7fa'],
    tokens: {
      ...SHARED,
      paper: '#e9f1fd',
      'paper-2': '#f4f0fd',
      'paper-3': '#e6f7f6',
      'paper-grid': 'rgba(74, 110, 170, 0.16)',
      surface: '#fdfeff',
      'surface-2': '#e2ecfa',
      bar: '#bfe3f7',
      'bar-2': '#d3d7fa',
      ink: '#3f6199',
      'ink-2': '#5878ac',
      'ink-3': '#7a95c2',
      line: '#cfdff5',
      accent: '#a9cdf5',
      'accent-2': '#8fbcf0',
      'accent-ink': '#22406e',
      danger: '#c2566d',
      'tone-a': '#bfe3f7',
      'tone-b': '#d3d7fa',
      'tone-c': '#c9f0e4',
      'tone-d': '#fbe4b8',
      'tone-e': '#f7c9dd',
      'tone-ink': '#22406e',
      'tier-low': '#c9f0e4',
      'tier-medium': '#bfe3f7',
      'tier-high': '#fbe4b8',
      'art-s': '52%',
      'art-l': '86%',
      'art-ink': '#3f6199',
      'shadow-color': '#93b4de',
      'badge-ink': '#22406e',
    },
  },
  {
    id: 'matcha',
    name: 'Matcha',
    blurb: 'Soft green, butter windows.',
    scheme: 'light',
    swatch: ['#eefaf0', '#c7edd2', '#fdeeb4'],
    tokens: {
      ...SHARED,
      paper: '#eefaf0',
      'paper-2': '#fdf8e3',
      'paper-3': '#f5f9e6',
      'paper-grid': 'rgba(76, 130, 96, 0.14)',
      surface: '#fdfffb',
      'surface-2': '#e3f4e6',
      bar: '#c7edd2',
      'bar-2': '#fdeeb4',
      ink: '#47765a',
      'ink-2': '#5f8d72',
      'ink-3': '#82a891',
      line: '#d3ead8',
      accent: '#b3e3c1',
      'accent-2': '#9bd8ac',
      'accent-ink': '#26492f',
      danger: '#c26b52',
      'tone-a': '#c7edd2',
      'tone-b': '#fdeeb4',
      'tone-c': '#cfe6f7',
      'tone-d': '#f8cfd8',
      'tone-e': '#ded3f2',
      'tone-ink': '#26492f',
      'tier-low': '#c7edd2',
      'tier-medium': '#cfe6f7',
      'tier-high': '#fdeeb4',
      'art-s': '48%',
      'art-l': '86%',
      'art-ink': '#47765a',
      'shadow-color': '#8fc7a0',
      'badge-ink': '#26492f',
    },
  },
  {
    id: 'nightlight',
    name: 'Night Light',
    blurb: 'Dim room, pastel screen.',
    scheme: 'dark',
    swatch: ['#221a33', '#c3a8ff', '#7de0c0'],
    tokens: {
      ...SHARED,
      paper: '#221a33',
      'paper-2': '#2b2140',
      'paper-3': '#1c1a30',
      'paper-grid': 'rgba(198, 170, 255, 0.10)',
      surface: '#2e2444',
      'surface-2': '#392c53',
      bar: '#493a68',
      'bar-2': '#563f78',
      ink: '#f0e6ff',
      'ink-2': '#cfc0ea',
      'ink-3': '#a294c4',
      line: '#493a68',
      accent: '#d9a7ec',
      'accent-2': '#c98fe0',
      'accent-ink': '#2a1440',
      danger: '#ff8fae',
      'tone-a': '#7de0c0',
      'tone-b': '#ffa8cd',
      'tone-c': '#97c6ff',
      'tone-d': '#ffd98a',
      'tone-e': '#c3a8ff',
      // Titlebars stay pastel even at night, so their labels keep the dark ink
      // rather than following the theme's pale body ink.
      'tone-ink': '#2a1440',
      'tier-low': '#7de0c0',
      'tier-medium': '#97c6ff',
      'tier-high': '#ffd98a',
      'art-s': '62%',
      'art-l': '72%',
      'art-ink': '#2a1440',
      'shadow-color': '#120c1e',
      'badge-ink': '#2a1440',
    },
  },
]

export const DEFAULT_THEME = 'sticker'
export const getTheme = (id) => THEMES.find((t) => t.id === id) ?? THEMES[0]
