// Every visual decision in the app resolves to one of these tokens.
// Components never hardcode a color/radius/font - they read var(--token),
// and ThemeProvider writes the active theme's values onto :root.
//
// The house style is flat + outlined: solid fills, a single ink color doing
// borders and text, and a hard offset shadow (no blur, no gradients, no glow).
// Adding a theme = adding an entry here. Nothing else needs to change.

const DISPLAY = "'Fredoka', ui-rounded, 'Segoe UI', system-ui, sans-serif"
const BODY = "'Nunito', ui-sans-serif, system-ui, -apple-system, sans-serif"
const LABEL = "'DM Mono', ui-monospace, 'SF Mono', Menlo, monospace"

const SHARED = {
  'border-w': '2px',
  'shadow-off': '3px',
  'radius-lg': '18px',
  'radius-md': '12px',
  'radius-sm': '8px',
  'font-display': DISPLAY,
  'font-body': BODY,
  'font-label': LABEL,
  'display-weight': '600',
  'display-tracking': '-0.01em',
}

export const THEMES = [
  {
    id: 'sticker',
    name: 'Sticker Club',
    blurb: 'Blush paper, mint chrome.',
    scheme: 'light',
    swatch: ['#fdf1f3', '#b8e6d5', '#f4b8c8'],
    tokens: {
      ...SHARED,
      paper: '#fdf1f3',
      'paper-grid': 'rgba(158, 92, 110, 0.09)',
      surface: '#fffdfd',
      'surface-2': '#fbe9ee',
      bar: '#c9ece0',
      'bar-2': '#f7dbe3',
      ink: '#7b4a58',
      'ink-2': '#96636f',
      'ink-3': '#a97e88',
      line: '#f0d5dd',
      accent: '#f4b8c8',
      'accent-2': '#efa4b8',
      'accent-ink': '#6d3d4a',
      danger: '#c2566d',
      'tier-low': '#b8e6d5',
      'tier-medium': '#bdd4f5',
      'tier-high': '#f8dd9a',
      'art-s': '58%',
      'art-l': '86%',
      'art-ink': '#7b4a58',
      'shadow-color': '#7b4a58',
      'badge-ink': '#5c3541',
    },
  },
  {
    id: 'notepad',
    name: 'Notepad',
    blurb: 'Cream page, cocoa ink.',
    scheme: 'light',
    swatch: ['#f7f0e2', '#e8c9a0', '#a8bf94'],
    tokens: {
      ...SHARED,
      paper: '#f7f0e2',
      'paper-grid': 'rgba(107, 82, 58, 0.1)',
      surface: '#fffcf5',
      'surface-2': '#f2e7d3',
      bar: '#e8c9a0',
      'bar-2': '#f0dcbd',
      ink: '#5b4636',
      'ink-2': '#7a6047',
      'ink-3': '#94795c',
      line: '#e6d8c0',
      accent: '#a8bf94',
      'accent-2': '#96b07f',
      'accent-ink': '#33422a',
      danger: '#b0563c',
      'tier-low': '#c3d9b0',
      'tier-medium': '#b9cfd9',
      'tier-high': '#eecb84',
      'art-s': '46%',
      'art-l': '84%',
      'art-ink': '#5b4636',
      'shadow-color': '#5b4636',
      'badge-ink': '#4a3728',
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    blurb: 'Grid paper, navy lines.',
    scheme: 'light',
    swatch: ['#e6ecfb', '#ffffff', '#f2b880'],
    tokens: {
      ...SHARED,
      paper: '#e6ecfb',
      'paper-grid': 'rgba(58, 74, 122, 0.14)',
      surface: '#ffffff',
      'surface-2': '#eef2fd',
      bar: '#bfd0f2',
      'bar-2': '#dde5fa',
      ink: '#3a4a7a',
      'ink-2': '#556699',
      'ink-3': '#6f7fb0',
      line: '#dbe3f7',
      accent: '#f2b880',
      'accent-2': '#eaa668',
      'accent-ink': '#4a3018',
      danger: '#c25a5a',
      'tier-low': '#a8dcc6',
      'tier-medium': '#b3c6f0',
      'tier-high': '#f2c98a',
      'art-s': '54%',
      'art-l': '87%',
      'art-ink': '#3a4a7a',
      'shadow-color': '#3a4a7a',
      'badge-ink': '#2c3a63',
    },
  },
  {
    id: 'matcha',
    name: 'Matcha',
    blurb: 'Soft green, warm cream.',
    scheme: 'light',
    swatch: ['#eef3e4', '#fffdf6', '#dba9a0'],
    tokens: {
      ...SHARED,
      paper: '#eef3e4',
      'paper-grid': 'rgba(74, 92, 60, 0.11)',
      surface: '#fffdf6',
      'surface-2': '#e7eedb',
      bar: '#cadcb4',
      'bar-2': '#e3ecd4',
      ink: '#46583a',
      'ink-2': '#63754f',
      'ink-3': '#7e8f68',
      line: '#dde6cd',
      accent: '#dba9a0',
      'accent-2': '#cf958b',
      'accent-ink': '#4a2b26',
      danger: '#b35a4d',
      'tier-low': '#c6e0b4',
      'tier-medium': '#b6d3d9',
      'tier-high': '#eccf92',
      'art-s': '44%',
      'art-l': '85%',
      'art-ink': '#46583a',
      'shadow-color': '#46583a',
      'badge-ink': '#36452c',
    },
  },
  {
    id: 'nightlight',
    name: 'Night Light',
    blurb: 'Dim room, pastel screen.',
    scheme: 'dark',
    swatch: ['#22202e', '#2e2b3f', '#b9a8f0'],
    tokens: {
      ...SHARED,
      paper: '#22202e',
      'paper-grid': 'rgba(214, 205, 245, 0.07)',
      surface: '#2e2b3f',
      'surface-2': '#3a3650',
      bar: '#413c5c',
      'bar-2': '#37334d',
      ink: '#ded7f2',
      'ink-2': '#b6adcf',
      'ink-3': '#9990b3',
      line: '#443f5e',
      accent: '#b9a8f0',
      'accent-2': '#a894e8',
      'accent-ink': '#241d3d',
      danger: '#f0a0b4',
      'tier-low': '#8fd6bb',
      'tier-medium': '#9fb8ee',
      'tier-high': '#efc887',
      'art-s': '30%',
      'art-l': '41%',
      'art-ink': '#f2eeff',
      'shadow-color': '#14121c',
      'badge-ink': '#241d3d',
    },
  },
]

export const DEFAULT_THEME = 'sticker'
export const getTheme = (id) => THEMES.find((t) => t.id === id) ?? THEMES[0]
